# databases:
#   - name: mysite
#     databaseName: mysite
#     user: mysite

services:
  - type: web
    name: djangotest
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn djangotest.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
